### PR TITLE
add CUDA mining support

### PR DESCRIPTION
**Pull request by asdvxgxasjab**
Tested on Linux Ubuntu 18.10. ~~Haven't been able to test with multiple cards yet though.~~ Successfully tested with 2 Tesla v100s.

### CODE REVIEW

**Comment by asdvxgxasjab** [comment]
~~Note there seems to be an issue when using with a host that has more than 1 GPU device. Investigating.~~ Bug should be fixed.

**Comment by johnnytwoshankes** [comment]
Nice update. Is there any plan to include the most recent architecture (Turing)? I believe it is SM 7.5

**Comment by asdvxgxasjab** [comment]
> Nice update. Is there any plan to include the most recent architecture (Turing)? I believe it is SM 7.5

I think it should work. The function in there that translates SM version to cores isn't even used right now. I'll probably remove it.

**Comment by rigamp** [comment]
RTX (Turing) hashes. Have a rig w 1070 tis and 2070s. Would be nice if logs could show hashrate per GPU to see Turing vs Pascal performance.

**Comment by asdvxgxasjab** [comment]
This might be useful for some people. From the #help channel on Discord:

<pre>
a workaround for the cmake install is to just edit the CMakeLists.txt
in cruzbit/cuda and change the first line that says VERSION 3.12 to VERSION 3.10
and then you can just use default ubuntu cmake version
you can also install the latest go with snap: sudo snap install go --classic
</pre>

**Comment by johnnytwoshankes** [comment]
@asdvxgxasjab, since this #25 was merged into master, following the directions given for enabling cuda no longer work. cuda/BUILDING.md directions do not provide any different functionality over the existing cpu based code.

**Comment by asdvxgxasjab** [comment]
> @asdvxgxasjab, since this #25 was merged into master, following the directions given for enabling cuda no longer work. cuda/BUILDING.md directions do not provide any different functionality over the existing cpu based code.

Hmm. Does your client start up and log "CUDA initialized" when you run it?

**Comment by johnnytwoshankes** [comment]
No, it behaves just like it would for standard cpu mining. I was looking through the code base, but could not find a flag that can be passed on start.

**Pull request merged**
